version: '3.9'
services:

  service-one:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "45080:65080"
      - "45081:65081"
      - "45060:65060"
    networks:
      - hey

  service-two:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "55080:65080"
      - "55081:65081"
      - "55060:65060"
    networks:
      - hey

networks:
  hey: null
