name: 'Setup the Go environment'
description: 'Installs go and restores/saves the build/module cache'
inputs:
  go-version:
    required: true
runs:
  using: "composite"
  steps:
  - name: Set up Go
    uses: actions/setup-go@v3
    with:
      go-version: ${{ inputs.go-version }}

  - name: Check out code into the Go module directory
    uses: actions/checkout@v3
    with:
      # For pull requests, build and test the PR head not a merge of the PR with the destination.
      ref: ${{ github.event.pull_request.head.sha || github.ref }}
      # We need to full history for git-restore-mtime to know what modification dates to use.
      # Otherwise, the Go test cache will fail (due to the modification time of fixtures changing).
      fetch-depth: '0'

  # Restore original modification time of files based on the date of the most
  # recent commit that modified them as mtimes affect the Go test cache.
  - name: Restore modification time of checkout files
    shell: bash
    run: |
      # Set a base, fixed modification time of all directories.
      # git-restore-mtime doesn't set the mtime of all directories.
      # (see https://github.com/MestreLion/git-tools/issues/47 for details)
      touch -m -t '201509301646' $(find . -type d -not -path '.git/*')
      # Restore original modification time from git. git clone sets the
      # modification time to the current time, but Go tests that access fixtures
      # get invalidated if their modification times change.
      sudo apt-get install -y git-restore-mtime
      git restore-mtime

  # The PREFIX must uniquely identify the specific instance of a job executing.
  - shell: bash
    run: echo 'PREFIX=${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ inputs.go-version }}-matrix(${{ join(matrix.*,'|') }})' >> $GITHUB_ENV

  # Cache the Go Modules downloaded during the job.
  - uses: actions/cache@v3
    with:
      # * Module download cache
      #
      # The cache key looks like:
      #   `goweb ci-run_tests-Linux-1.18-matrix(1.18|ubuntu-22.04)-go-mod-<hash>`
      # The restore key looks like:
      #   `goweb ci-run_tests-Linux-1.18-matrix(1.18|ubuntu-22.04)-go-mod-`
      #
      path: ~/go/pkg/mod
      key: ${{ env.PREFIX }}-go-mod-${{ hashFiles('**/go.sum') }}
      restore-keys: ${{ env.PREFIX }}-go-mod-

  # Cache any build and test artifacts during the job, which will speed up
  # rebuilds and cause test runs to skip tests that have no reason to rerun.
  - uses: actions/cache@v3
    with:
      # In order:
      # * Build cache (Linux)
      # * Build cache (Mac)
      # * Build cache (Windows)
      #
      # The cache key looks like:
      #   `goweb ci-run_tests-Linux-1.18-matrix(1.18|ubuntu-22.04)-go-build-refs/pull/24/merge-<hash>`
      # The restore key looks like:
      #   `goweb ci-run_tests-Linux-1.18-matrix(1.18|ubuntu-22.04)-go-build-`
      #
      path: |
        ~/.cache/go-build
        ~/Library/Caches/go-build
        ~\AppData\Local\go-build 
      key: ${{ env.PREFIX }}-go-build-${{ github.ref }}-${{ hashFiles('**', '!.git') }}
      restore-keys: |
        ${{ env.PREFIX }}-go-build-${{ github.ref }}-
        ${{ env.PREFIX }}-go-build-

  # Reset the cache for main/protected branches, to ensure they build and run the tests from zero
  # and that the module cache is cleaned (otherwise it accumulates orphan dependencies over time).
  - if: github.ref_protected
    shell: bash
    run: sudo rm -rf ~/go/pkg/mod ~/.cache/go-build ~/Library/Caches/go-build ~\AppData\Local\go-build
